FROM almalinux:8

RUN dnf -y update

# Install compulsory tools
# ==============================================================
#RUN dnf -y install epel-release &&\
#    dnf -y install gcc-c++ &&\
#    dnf -y install automake &&\
#    dnf -y install kernel-devel &&\
#    dnf -y install openssl-devel &&\
#    dnf -y install wget &&\
#    dnf -y install make

# Install dev libs & tools (for R)
# ==============================================================
RUN dnf -y install gfortran &&\
    dnf -y install libbz2-devel &&\
    dnf -y install liblzma-dev &&\
    dnf -y install libpcre++-devel &&\
    dnf -y install texlive-latex-extra &&\
    dnf -y install texlive-fonts-extra &&\
    dnf -y install libfontconfig1-dev &&\
    dnf -y install libxml2-devel &&\
    dnf -y install libharfbuzz-devel &&\
    dnf -y install libfribidi-devel &&\
    dnf -y install libfreetype6-devel &&\
    dnf -y install libpng-devel &&\
    dnf -y install libjpeg-devel &&\
    dnf -y install libtiff5-devel &&\
    dnf -y install libcurl4-openssl-devel &&\
    dnf -y install tzdata &&\
    dnf -y install libcairo2-devel &&\
    dnf -y install libxt-devel

# Install dev libs & tools (for git)
# ==============================================================
RUN dnf -y install zlib-devel &&\
    dnf -y install libexpat1-dev

# Install dev libs & tools (for swigex)
# ==============================================================
RUN dnf -y install doxygen

# Install 'recent' cmake (from source)
# ==============================================================
# https://orcacore.com/install-use-cmake-almalinux-8
RUN wget https://cmake.org/files/v3.20/cmake-3.20.6.tar.gz &&\
    tar -zxvf cmake-3.20.6.tar.gz &&\
    cd cmake-3.20.6 &&\
    ./bootstrap &&\
    gmake &&\
    make install

# Install recent git (from source)
# ==============================================================
RUN wget https://github.com/git/git/archive/refs/tags/v2.34.1.tar.gz &&\
    tar -zxf v2.34.1.tar.gz &&\
    cd git-2.34.1 &&\
    make prefix=/usr/local all &&\
    make prefix=/usr/local install

# Install non-official pre-build swig
# ==============================================================
RUN wget https://pierre.guillou.net/data/swig.tar.gz &&\
    tar zxvf swig.tar.gz &&\
    chmod +x swig-ors/bin/swig

# Install last version of R (from source)
# ==============================================================
RUN wget https://cran.r-project.org/src/base/R-4/R-4.5.0.tar.gz &&\
    tar -xvf R-4.5.0.tar.gz &&\
    cd R-4.5.0 &&\
    ./configure --with-readline=no --without-x --with-cairo --with-pcre1 --enable-R-shlib &&\
    make &&\
    make install &&\
    Rscript -e "install.packages (c('knitr', 'rmarkdown'), repos='https://cloud.r-project.org/', dependencies = TRUE)" &&\
    Rscript -e "install.packages(c('roxygen2'), repos='https://cloud.r-project.org/', dependencies = TRUE)"

#RUN export PATH=/swig-ors/bin:$PATH &&\
#    swig --version

