FROM almalinux:8

# UPDATE repo
RUN dnf -y update && dnf -y install epel-release && dnf clean all

# INSTALL dependencies
RUN dnf -y install \
    sudo wget diffutils make gcc-c++ gettext unzip \
    zlib-devel libffi-devel sqlite-devel openssl-devel \
    gcc-gfortran bzip2-devel xz-devel \
    fontconfig-devel libxml2-devel \
    harfbuzz-devel fribidi-devel freetype-devel libpng-devel \
    libjpeg-turbo-devel libtiff-devel libcurl-devel tzdata \
    cairo-devel libXt-devel \
    python3 flex \
    git cmake gzip xz which
    
# INSTALL recent pcre2
RUN git clone --branch pcre2-10.47 https://github.com/PCRE2Project/pcre2.git && \
    cd pcre2 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON && \
    make && \
    make install && \
    cd .. && \
    rm -rf pcre2

# INSTALL recent bison
RUN dnf -y install m4 wget tar && \
    wget http://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz && \
    tar -xvzf bison-3.8.2.tar.gz && \
    cd bison-3.8.2 && \
    ./configure --prefix=/usr/local && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf bison-3.8.2*

# INSTALL Doxygen
RUN git clone --branch Release_1_9_8 https://github.com/doxygen/doxygen.git && \
    cd doxygen && \
    mkdir build && cd build && \
    cmake -G "Unix Makefiles" .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf doxygen

# INSTALL recent R
RUN wget https://cran.r-project.org/src/base/R-4/R-4.6.0.tar.gz && \
    tar -xvf R-4.6.0.tar.gz && \
    cd R-4.6.0 && \
    ./configure --with-readline=no --without-x --with-cairo --with-pcre1 --enable-R-shlib && \
    make && \
    make install && \
    Rscript -e "install.packages (c('knitr', 'rmarkdown', 'roxygen2'), repos='https://cloud.r-project.org/', dependencies = TRUE)" && \
    cd .. && \
    rm -rf R-4.6.0*

# INSTALL SWIG
RUN git clone https://github.com/fabien-ors/swig && \
    cd swig && \
    cmake -Bbuild && \
    cd build && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf swig

